// Code generated by MockGen. DO NOT EDIT.
// Source: room.go

// Package mock_mysql is a generated GoMock package.
package mock_mysql

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/iPolyomino/Kamen-Rider-NAGANO-Server/internal/mysql/model"
	gorm "github.com/jinzhu/gorm"
	reflect "reflect"
)

// MockRoom is a mock of Room interface
type MockRoom struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMockRecorder
}

// MockRoomMockRecorder is the mock recorder for MockRoom
type MockRoomMockRecorder struct {
	mock *MockRoom
}

// NewMockRoom creates a new mock instance
func NewMockRoom(ctrl *gomock.Controller) *MockRoom {
	mock := &MockRoom{ctrl: ctrl}
	mock.recorder = &MockRoomMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRoom) EXPECT() *MockRoomMockRecorder {
	return m.recorder
}

// Find mocks base method
func (m *MockRoom) Find(tx *gorm.DB, roomID int) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", tx, roomID)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockRoomMockRecorder) Find(tx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRoom)(nil).Find), tx, roomID)
}
