version: "2.4"

services:
  imageboard_db:
    image: mysql:8.0.20
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    networks:
      - imageboard_network
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD-SHELL", "mysqlshow -u root -proot"]
      interval: "5s"
      retries: 10
    container_name: imageboard_db

  imageboard_db_waiter:
    image: alpine:3.10
    entrypoint: env
    depends_on:
      imageboard_db:
        condition: service_healthy
    networks:
      - imageboard_network
    container_name: imageboard_db_waiter

networks:
  imageboard_network:
    driver: bridge